### ISSUE TITLE
Add Options?

### ISSUE THREAD

**Issue by but-i-am-dominator** [tarahmarie/target_file_generator#1]
Are you trying to keep this as simple as possible or add options / features?

(I really like this idea but, this version doesnt account for network ips, subnets, VLSM, or anything that isn't a /24. )

Are you looking to add those types of things?

**Comment by tarahmarie** [comment]
Absolutely. Options are welcome; I was anticipating more error handling at first :)

**Comment by but-i-am-dominator** [comment]
Excellent!
